# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/brett/Programming/School/CPE_133/final/Binary_to_BCD/Binary_to_BCD.cache/wt [current_project]
set_property parent.project_path /home/brett/Programming/School/CPE_133/final/Binary_to_BCD/Binary_to_BCD.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  /home/brett/Programming/School/CPE_133/final/Binary_to_BCD/Binary_to_BCD.srcs/sources_1/new/Bin2Hex.vhd
  /home/brett/Programming/School/CPE_133/final/Binary_to_BCD/Binary_to_BCD.srcs/sources_1/new/Binary_to_BCD.vhd
  /home/brett/Programming/School/CPE_133/final/Binary_to_BCD/Binary_to_BCD.srcs/sources_1/new/Counter_Wrapper.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/brett/Programming/School/CPE_133/final/Binary_to_BCD/Binary_to_BCD.srcs/constrs_1/Bin2Hex_Const.xdc
set_property used_in_implementation false [get_files /home/brett/Programming/School/CPE_133/final/Binary_to_BCD/Binary_to_BCD.srcs/constrs_1/Bin2Hex_Const.xdc]


synth_design -top Counter_Wrapper -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Counter_Wrapper.dcp

catch { report_utilization -file Counter_Wrapper_utilization_synth.rpt -pb Counter_Wrapper_utilization_synth.pb }
