webtalk_init -webtalk_dir /home/brett/Programming/School/CPE_133/final/Binary_to_BCD/Binary_to_BCD.sim/sim_1/behav/xsim.dir/Binary_to_BCD_SIM_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Nov 21 11:48:48 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1577090" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "35aaccdf-b680-4818-b01b-b8bba6e7a3a2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2f17d5f280b3405ebc1bf2f5da894be1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "16" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2700.281 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "134804_KB" -context "xsim\\usage"
webtalk_transmit -clientid 618300539 -regid "" -xml /home/brett/Programming/School/CPE_133/final/Binary_to_BCD/Binary_to_BCD.sim/sim_1/behav/xsim.dir/Binary_to_BCD_SIM_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/brett/Programming/School/CPE_133/final/Binary_to_BCD/Binary_to_BCD.sim/sim_1/behav/xsim.dir/Binary_to_BCD_SIM_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/brett/Programming/School/CPE_133/final/Binary_to_BCD/Binary_to_BCD.sim/sim_1/behav/xsim.dir/Binary_to_BCD_SIM_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
