# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tlcpg236-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/brett/Button/Button.cache/wt [current_project]
set_property parent.project_path /home/brett/Button/Button.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  /home/brett/Button/Button.srcs/sources_1/new/Button.vhd
  /home/brett/Button/Button.srcs/sources_1/new/Button_Test.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/brett/Button/Button.srcs/constrs_1/new/Button_Constraints.xdc
set_property used_in_implementation false [get_files /home/brett/Button/Button.srcs/constrs_1/new/Button_Constraints.xdc]


synth_design -top Button_Test -part xc7a35tlcpg236-2L


write_checkpoint -force -noxdef Button_Test.dcp

catch { report_utilization -file Button_Test_utilization_synth.rpt -pb Button_Test_utilization_synth.pb }
