----------------------------------------------
-- Project : CPE 133 Final Project

-- Module Name : Comparator
-- Authors : Collin Kenner, Brett Glidden

-- Description : compares the current user inputs on
--      the switchboard to the pattern generated by
--      the pattern generation module
----------------------------------------------

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.numeric_std.ALL;

-- Define comparator module
-- Inputs
--      reset : hard comparator reset
--      user_input : user switch positions
--      pattern : pattern to match from pattern generation module
--      bitmask : bitmask based on user difficulty
-- Outputs
--      result : the output of (user_input == pattern)
entity Comparator is
    Port (reset : in STD_LOGIC;
          user_input : in STD_LOGIC_VECTOR(15 downto 0);
          pattern : in STD_LOGIC_VECTOR(15 downto 0);
          bitmask : in STD_LOGIC_VECTOR(15 downto 0);
          result : out STD_LOGIC);
end Comparator;

architecture arch_Comparator of Comparator is
   
    -- High when user_input = pattern
    signal cmp_flag : STD_LOGIC := '0';
    
    -- Adjust the user input to the difficulty
    signal adjusted_input : STD_LOGIC_VECTOR(15 downto 0);

    -- Adjust the pattern to the difficulty
    signal adjusted_pattern : STD_LOGIC_VECTOR(15 downto 0);
    
begin
    -- Bitmask user inputs for difficutly
    adjusted_input <= user_input AND bitmask;
    adjusted_pattern <= pattern AND bitmask;
   
    -- Comapre user input to the pattern
    compareInputs : process (adjusted_input, adjusted_pattern, reset) 
    begin
        if (reset = '1') then
            cmp_flag <= '0';
        elsif (adjusted_input = adjusted_pattern) then
            cmp_flag <= '1';
        else
            cmp_flag <= '0';
        end if;
    end process;

    -- Tie result to cmp_flag (we should remove cmp_flag, it's redundant)
    result <= cmp_flag;
       
    
end arch_Comparator;
