webtalk_init -webtalk_dir C:/Users/ckenner/Desktop/CPE133-NoWinningAllowed-Finale/CPE133-NoWinningAllowed-Finale/Finale/Finale.sim/sim_1/behav/xsim.dir/sim_hell_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Dec 07 15:21:12 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1577090" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210778909_1777507066_210600704_321" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e4e58ebcfe8a5544aa1afab19a7a5ef9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a6de33d6223f433e8e1ec502fcb7cc1b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "22" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "181 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "6 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "121" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "56" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "28" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "0.89_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "45224_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4132029909 -regid "210778909_1777507066_210600704_321" -xml C:/Users/ckenner/Desktop/CPE133-NoWinningAllowed-Finale/CPE133-NoWinningAllowed-Finale/Finale/Finale.sim/sim_1/behav/xsim.dir/sim_hell_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/ckenner/Desktop/CPE133-NoWinningAllowed-Finale/CPE133-NoWinningAllowed-Finale/Finale/Finale.sim/sim_1/behav/xsim.dir/sim_hell_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/ckenner/Desktop/CPE133-NoWinningAllowed-Finale/CPE133-NoWinningAllowed-Finale/Finale/Finale.sim/sim_1/behav/xsim.dir/sim_hell_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
